### ISSUE TITLE
Add Caching To Travis Build 

### ISSUE THREAD

**Issue by alexfinnarn** [mradcliffe/xeroclient#5]
Adding caching should speed up the builds.

```yaml
cache:
  directories:
    - $HOME/.composer/cache/files
```

References:
- https://blog.wyrihaximus.net/2015/07/composer-cache-on-travis/
- https://docs.travis-ci.com/user/caching/
